version: '2'
services:
  cre-proxy:
    image: tamboraorg/creproxy
    container_name: creproxy
    environment:
      ADMIN_EMAIL: admin@example.com
      CRE_DOMAIN: example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./certs:/etc/letsencrypt/live"
    links:
      - jenkins2

  cre-nginx:
    image: tamboraorg/crenginx
    container_name: crenginx
    environment:
      CRE_SUBDOMAIN: www
    volumes:
        - ./volumes/html:/code
#        - ./nginx2/site.conf:/etc/nginx/conf.d/site.conf
        - ./volumes/php-nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - cre-php

  cre-php:
    image: tamboraorg/crephp
    container_name: crephp
    volumes:
      - ./volumes/html:/code
      - ./volumes/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
#  links:
#    - memcached2
#    - postgres2
#    - elasticsearch2

