version: '2'
services:
  cre-proxy:
    image: tamboraorg/creproxy
    container_name: creproxy
    environment:
      ADMIN_EMAIL: admin@example.com
      CRE_DOMAIN: example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./certs:/etc/letsencrypt"

  cre-nginx-php:
    image: tamboraorg/crenginxphp
    container_name: crenginxphp
    environment: 
      CRE_SUBDOMAIN: dev
    links: 
     - cre-php
    volumes_from:
     - cre-php

  cre-php:
    image: tamboraorg/crephp
    container_name: crephp
    environment:
      CRE_PHP_ROOT: www/sub
#    volumes:
#        - ./volumes/www:/cre/www
    links:
      - cre-mysql    
#    - memcached2
#    - postgres2
#    - elasticsearch2

  cre-mysql:
    image: tamboraorg/cremysql
    container_name: cremysql
    environment:
      MYSQL_ROOT_PWD: secret
      MYSQL_USER:     cre 
      MYSQL_USER_PWD: secret
      MYSQL_USER_DB:  cre  
      CRE_SUBDOMAIN:  db2
#      CRE_PORT:       3306 
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  cre-postgres:
    image: tamboraorg/crepostgis
    container_name: crepostgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      CRE_SUBDOMAIN:     db
      CRE_PORT:          5432
      POSTGRES_USER:     cre
      POSTGRES_PASSWORD: secret
      POSTGRES_DB:       cre

  cre-nextcloud:
    image: tamboraorg/crenextcloud
    container_name: crenextcloud
    environment: 
      CRE_SUBDOMAIN: box
      CRE_PORT: 9000
    links:
        - cre-lpostgres
    volumes:
        - ./nextcloud/apps:/var/www/html/apps
        - ./nextcloud/config:/var/www/html/config
        - ./nextcloud/data:/var/www/html/data

# docker-compose  --file dc-clim.yml up -d

