version: '2'
services:
  cre-proxy:
    image: tamboraorg/creproxy
    container_name: creproxy
    environment:
      ADMIN_EMAIL: admin@example.com
      CRE_DOMAIN: example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./certs:/etc/letsencrypt/live"

  cre-nginx:
    image: tamboraorg/crephp
    container_name: crephp
    environment:
      CRE_SUBDOMAIN: www
    volumes:
        - ./volumes/www:/cre/www
#        - ./nginx2/site.conf:/etc/nginx/conf.d/site.conf
#        - ./volumes/php-nginx.conf:/etc/nginx/conf.d/default.conf
#  links:
#    - memcached2
#    - postgres2
#    - elasticsearch2

